When forking with `--workers 10` requests was sharing the session, which is not safe. I believe this is the cause of the reported
```
RPCError: Received null response from remote scheduler
```