fix azureblob tests: use json instead of numpy (#3032)
Numpy is not installed in the current setup

It fixes these errors:

```
  File "/home/travis/build/spotify/luigi/test/contrib/azureblob_test.py", line 138, in run

    import numpy

ModuleNotFoundError: No module named 'numpy'
```
https://travis-ci.org/github/spotify/luigi/jobs/754449469

The test silently failed, asserts weren't covered
Added an assert checking the output of FinalTask