Add sqlalchemy as deb build dependency
I verified that this works by running this on Spotify's internal build
agents. Previous builds were failing with message

    AttributeError: 'module' object has no attribute 'SkipTest'

Because db_task_history couldn't be loaded.